### ISSUE TITLE
media: Add content from libp2p Day

### ISSUE THREAD

**Issue by p-shahi** [libp2p/website#157]
## Done Criteria

Latest videos from [libp2p Day](https://2022.ipfs.camp/#Libp2p-Day) are added to https://libp2p.io/media/

**Introductions & Project Updates** needs to add
- [x] `Intro to libp2p: helping with real world application problems`
- [x] `A month in PL EngRes libp2p Development and how you can be involved`

Create a new **Browser Connectivity** section and add
- [x] `Browser connectivity state of the union and demo`
- [x] `Why WebRTC`

**Technical Deep Dives** needs to add
- [x] `libp2p Interoperability Testing with Testground`
- [x] `DOS defense - do’s and dont’s`
- [x] `Decentralized NAT Hole-Punching`
- [x] `The power of two choices`

Create a new **Community** section and add
- [x] `libp2p in Nim`
- [x] `How Pyrsia is using libp2p to take over the world`
- [x] `Satellite.im and what we're doing with IPFS and js-libp2p`
- [x] `Intro to Lodestar`
 
## Why Important

These videos contain the most up to date information about project status/implementation timelines

**Comment by BigLep** [comment]
@p-shahi : I couple of thoughts on this:
1. It would be ideal to get a link to our YouTube channel I think: https://www.youtube.com/@libp2p630
2. I would elevate Juan's talk over mine.  (I'm also not sure how relevant my talk is given it's more EngRes-centered rather than the product libp2p project.)
